languageCode = "zh-cn"
title = "陈伟律师"
baseurl = "http://xlking.com/"
theme = "aerial"

[params]
cwimg = "/css/images/cw.jpg"
  name = "陈 伟"
  about = "律师 | TEl:13975892485 | 1982.03 | 执业证号:"
  copyright = "ChenWei.All Rights Reserved 2018-2030"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "/css/images/favicon.ico"

#[[params.social]]
 # medium = "Twitter"
 # icon = "twitter"
 # link = "#"

#[[params.social]]
 # medium = "Facebook"
 # icon = "facebook"
 # link = "#"

#[[params.social]]
 # medium = "Dribbble"
 # icon = "dribbble"
 # link = "#"

[[params.social]]
  medium = "Qq"
  icon = "qq"
  link = "http://wpa.qq.com/msgrd?v=3&uin=47925738&site=qq&menu=yes"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:cw.law@qq.com"
